language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn run build && yarn run test:prod
after_success:
  - yarn run travis-deploy-once "yarn run report-coverage"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
